In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
arr1=np.array((1,2,3,4,5))
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])

print(arr1)
print(arr2)
print(arr3)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


In [6]:
import numpy as np
a=np.array(42)
b=np.array((1,2,3,4,5))
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimensions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [12]:
import numpy as np
arr=np.array([23,20,3,40])
print(arr[1]+arr[2])

23


In [9]:
import numpy as np
array2d=np.array([[10,22,47],[23,78,90],[100,101,103]])
print(array2d)
print(array2d[2,1])
print(array2d[2,0:2])
print(array2d[:,2])

[[ 10  22  47]
 [ 23  78  90]
 [100 101 103]]
101
[100 101]
[ 47  90 103]


In [31]:
import numpy as np
array3d=np.array([[[11,9,24],[44,57,65]],[[32,35,33],[45,47,48]]])
print(array3d)
print(array3d[-2,-1,-2])

[[[11  9 24]
  [44 57 65]]

 [[32 35 33]
  [45 47 48]]]
57


In [43]:
import numpy as np
arr=np.array([5,7,10,3,6,8,20,24,25])
print(arr[-8:-4:2])

[7 3]


In [44]:
import numpy as np
arr=np.array([5,7,10,3,6,8,20,24,25])
print(arr[::2])

[ 5 10  6 20 25]


In [62]:
import numpy as np
a=np.array([[4,7,8,2],[1,6,8,15],[17,77,88,64]])
#print(a[0:2,3])
print(a[0:2,0:3])


[[4 7 8]
 [1 6 8]]


In [63]:
import numpy as np
arr=np.array([5,7,10,3,6,8,20,24,25])
print(arr.dtype)

int32


In [64]:
import numpy as np
arr=np.array(["apple","banana","cherry"])
print(arr.dtype)

<U6


In [65]:
import numpy as np
arr=np.array([5,7,10,3,6,8,20,24,25],dtype="S")
print(arr)
print(arr.dtype)

[b'5' b'7' b'10' b'3' b'6' b'8' b'20' b'24' b'25']
|S2


In [66]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[1]=47
print(arr)
print(x)

[ 1 47  3  4  5]
[1 2 3 4 5]


In [68]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
x[2]=47
print(arr)
print(x)

[ 1  2 47  4  5]
[ 1  2 47  4  5]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [3]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [8]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [10]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [13]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [14]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)
    

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)
    

1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [17]:
import numpy as np
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [18]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [19]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [23]:
import numpy as np
arr1=np.array([[1,2,3],[7,8,9]])
arr2=np.array([[4,5,6],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr1)
print(arr2)
print(arr)

[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]
[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [24]:
import numpy as np
arr1=np.array([[1,2,3],[7,8,9]])
arr2=np.array([[4,5,6],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr1)
print(arr2)
print(arr)

[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [29]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1)
print(arr2)
arr=np.stack((arr1,arr2))
print(arr)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [30]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1)
print(arr2)
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [31]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1)
print(arr2)
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [32]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1)
print(arr2)
arr=np.vstack((arr1,arr2))
print(arr)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [33]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1)
print(arr2)
arr=np.dstack((arr1,arr2))
print(arr)

[1 2 3]
[4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5]


In [7]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)
print(newarr[0])
print(newarr[2])
print(newarr[1])


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[ 9 10]
 [11 12]]
[[5 6]
 [7 8]]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

print(arr)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=0)

print(arr)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [14]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

newarr = np.dsplit(arr, 3)

print(newarr)

[array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]],

       [[14],
        [17]]]), array([[[ 3],
        [ 6]],

       [[ 9],
        [12]],

       [[15],
        [18]]])]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [18]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [19]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [20]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [21]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(arr)

print(np.sort(arr))

[3 2 0 1]
[0 1 2 3]


In [22]:
import numpy as np
arr=np.array(["banana","cherry","apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [23]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [24]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [25]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [26]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [28]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False  True False  True False  True False]
[2 4 6]
