In [10]:
from scipy import constants
print(constants.giga)
print(constants.mebi)
print(constants.gram)
print(constants.degree)
print(constants.hour)
print(constants.inch)
print(constants.atmosphere)

print(dir(constants))

1000000000.0
1048576
0.001
0.017453292519943295
3600.0
0.0254
101325.0
['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp

In [11]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([0,0,0,0,0,1,1,0,2])
print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [12]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,0,1],[1,0,2]])
print(csr_matrix(arr).data)

[1 1 2]


In [13]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,0,1],[1,0,2]])
print(csr_matrix(arr).count_nonzero())

3


In [14]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,0,1],[1,0,2]])
mat=csr_matrix(arr)
mat.eliminate_zeros()
print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [15]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,0,1],[1,0,2]])
mat=csr_matrix(arr)
mat.sum_duplicates()
print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [16]:
import numpy as np
from scipy.sparse import csr_matrix
arr=np.array([[0,0,0],[0,0,1],[1,0,2]])
mat=csr_matrix(arr).tocsc()

print(mat)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2


In [17]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr=np.array([[0,1,2],[1,0,0],[2,0,0]])
newarr=csr_matrix(arr)
print(connected_components(newarr))

(1, array([0, 0, 0]))


In [23]:
import numpy as np

from scipy.interpolate import interp1d

xs=np.arange(10)
ys=2*xs + 1

f=interp1d(xs,ys)
xp=np.arange(2.1,3,0.1)
yp=f(xp)
print(xs)
print(ys)
print(xp)
print(yp)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8]


In [24]:
from scipy.interpolate import UnivariateSpline
import numpy as np

xs=np.arange(10)
ys=xs**2 + np.sin(xs) + 1

f=UnivariateSpline(xs,ys)

xp=np.arange(2.1,3,0.1)
yp=f(xp)

print(xs)
print(ys)

print(xp)
print(yp)

[0 1 2 3 4 5 6 7 8 9]
[ 1.          2.84147098  5.90929743 10.14112001 16.2431975  25.04107573
 36.7205845  50.6569866  65.98935825 82.41211849]
[2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[5.62826474 6.03987348 6.47131994 6.92265019 7.3939103  7.88514634
 8.39640439 8.92773053 9.47917082]


In [26]:
from scipy.interpolate import Rbf
import numpy as np

xs=np.arange(10)
ys=xs**2 + np.sin(xs) + 1

f=Rbf(xs,ys)

xp=np.arange(2.1,3,0.1)
yp=f(xp)

print(xs)
print(ys)

print(xp)
print(yp)

[0 1 2 3 4 5 6 7 8 9]
[ 1.          2.84147098  5.90929743 10.14112001 16.2431975  25.04107573
 36.7205845  50.6569866  65.98935825 82.41211849]
[2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[6.25748981 6.62190817 7.00310702 7.40121814 7.8161443  8.24773402
 8.69590519 9.16070828 9.64233874]
