In [3]:
import numpy as np
arr=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/6])
x=np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.5       ]


In [4]:
import numpy as np
arr=np.array([90,180,270,360])
x=np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [5]:
import numpy as np
arr=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/6])
x=np.rad2deg(arr)
print(x)

[90. 60. 45. 30.]


In [6]:
import numpy as np
x=np.arcsin(1.0)
print(x)

1.5707963267948966


In [7]:
import numpy as np
arr=np.array([1,-1,0.1])
x=np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [8]:
import numpy as np
base=3
perp=4
x=np.hypot(base,perp)
print(x)

5.0
