In [3]:
import numpy as np

def gssjrdn(a,b):
    
    a=np.array(a,float)
    b=np.array(b,float)
    n=len(b)
    
    # main loop
    
    for k in range(n):
        if np.fabs(a[k,k])<1.0e-12:
            for i in range(k+1,n):
                if np.fabs(a[i,k])>np.fabs(a[k,k]):
                    a[[k,i]]=a[[i,k]]
                    b[[k,i]]=b[[i,k]]
                    break
                    
        pivot=a[k,k]
        a[k]/=pivot
        b[k]/=pivot
        
        for i in range(n):
            if i==k or a[i,k]==0:
                continue
            factor=a[i,k]
            
            a[i]-=factor*a[k]
            b[i]-=factor*b[k]
    return b,a
    
    
a=[[0,2,0,1],[2,2,3,2],[4,-3,0,1],[6,1,-6,-5]]
b=[0,-2,-7,6]

X,A= gssjrdn(a,b)

print("The solution:")
print(X)
print("The transformed [a]:")
print(A)
    

The solution:
[-0.5         1.          0.33333333 -2.        ]
The transformed [a]:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [-0. -0. -0.  1.]]
